title: Scroll To Top
description: >- # this means to ignore newlines until "baseurl:"
  Scroll To Top/Bottom in a window
twitter_username: scrolltotp
github_username:  pratikabu
google_analytics: UA-10242165-
plugins:
  - jekyll-seo-tag
